#!/bin/sh
# below settings are only meant for testing, they are not safe for production use !!
# note, if you put "termcapinfo xterm* ti@:te@" in your ~/.screenrc you'll be able to scroll back easier
screen -S keosd -m /usr/local/bin/keosd \
	--http-server-address 0.0.0.0:8900 \
	--unlock-timeout 86400
